services:
  - type: web
    name: crm-cloud
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crm-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: crm-db
    databaseName: crm
    plan: free
