services:
  - type: web
    name: crm-cloud
    runtime: node
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && npm run build
    startCommand: npx prisma db push --accept-data-loss && npm run db:seed && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crm-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true

databases:
  - name: crm-db
    databaseName: crm
    plan: free
